# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

#virtualenv:
#    system_site_packages: true

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=pep8
    - python: 3.7
      dist: xenial
      env: TOXENV=pep8
    - python: 3.6
      env: TOXENV=pypi


before_script:
  - git clone https://github.com/ztombol/bats-support.git ../bats-support
  - git clone https://github.com/jasonkarns/bats-assert-1.git ../bats-assert-1

branches:
  only:
    - master
    - develop

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - make test
