# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

#virtualenv:
#    system_site_packages: true

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: pep
      env: TOXENV=pep
    - env: TOXENV=flake8

branches:
  only:
    - master

env:
  - TOXENV=pep
  - TOXENV=py36
  - TOXENV=py27

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install .
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - make test
