# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

#virtualenv:
#    system_site_packages: true

matrix:
  include:
    - python: 3.6
      dist: bionic
      env: TOXENV=py36
    - python: 3.7
      dist: bionic
      env: TOXENV=py37
    - python: 3.8
      dist: bionic
      env: TOXENV=py38
    - python: 3.8
      dist: bionic
      env: TOXENV=bandit
    - python: 3.8
      dist: bionic
      env: TOXENV=pep8
    - python: 3.8
      dist: bionic
      env: TOXENV=pypi


branches:
  only:
    - master
    - develop

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes conda  # Update CONDA without command line prompt
  - conda install -c conda-forge --yes tox
  # Useful for debugging any issues with conda
  - conda info -a

# command to run tests, e.g. python setup.py test
script:
  - make test
