# .github/workflows/publish.yml
name: Publish after Build

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    env:
      PY_COLORS: 1

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist

      # [1-publish-workflow]
      - name: Publish release candidate artifacts to TestPyPI
        if: contains(github.ref, 'rc') == true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PSEC_TEST_PYPI_PASSWORD }}
          packages-dir: ./dist
          verify-metadata: false

      - name: Publish tagged artifacts to PyPI
        if: contains(github.ref, 'rc') == false
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PSEC_PYPI_PASSWORD }}
          packages-dir: ./dist
          verify-metadata: false
      # ![1-publish-workflow]

